# Generated by Django 3.1.6 on 2021-04-20 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0002_auto_20210412_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotivator',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
