# Generated by Django 3.1.6 on 2021-04-20 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_module', '0003_auto_20210420_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_essays', to='books_module.bookmotivator'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_essays', to=settings.AUTH_USER_MODEL),
        ),
    ]
