# Generated by Django 3.1.6 on 2021-04-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0004_auto_20210412_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateforcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_certificate', to='courses_module.coursemotivator'),
        ),
    ]
