# Generated by Django 3.1.6 on 2021-04-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0006_auto_20210418_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_watched',
        ),
    ]
