# Generated by Django 3.1.6 on 2021-04-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_module', '0008_certificateforcourse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateforcourse',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
