# Generated by Django 3.1.6 on 2021-04-19 04:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_module', '0010_auto_20210419_1007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificateforcourse',
            unique_together={('course', 'user')},
        ),
    ]
