# Generated by Django 3.1.6 on 2021-04-12 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0003_auto_20210412_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemotivator',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
    ]
