# Generated by Django 3.1.6 on 2021-04-25 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0011_auto_20210419_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateforcourse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
