# Generated by Django 3.1.6 on 2021-03-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pages')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='Achieves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('reached', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='achieves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achieve',
                'verbose_name_plural': 'Achieves',
            },
        ),
    ]
