# Generated by Django 3.1.6 on 2021-04-08 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 8, 19, 4, 15, 542553), null=True),
        ),
    ]
