# Generated by Django 3.1.6 on 2021-04-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0009_auto_20210418_2151'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificates_for_courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_certificates_for_course', to='courses_module.certificateforcourse'),
        ),
    ]
