# Generated by Django 3.1.6 on 2021-04-09 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210409_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 9, 18, 35, 14, 526001), null=True),
        ),
    ]
