# Generated by Django 3.1.6 on 2021-04-09 12:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210409_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 9, 18, 38, 5, 503857), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30000)], verbose_name='Points'),
        ),
    ]
