# Generated by Django 3.1.6 on 2021-04-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_certificates_for_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certificates_for_courses',
        ),
    ]
