# Generated by Django 3.1.6 on 2021-03-29 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMotivator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('isbn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ISBN')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Pages')),
                ('created', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title')),
                ('essay', models.TextField(blank=True, max_length=1000)),
                ('essays', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='books_module.bookmotivator')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essay',
                'verbose_name_plural': 'Essays',
            },
        ),
    ]
