# Generated by Django 3.1.6 on 2021-03-29 11:37

from django.db import migrations
import books_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0002_auto_20210329_1051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookmotivator',
            managers=[
                ('objects', books_module.models.BookMotivatorManager()),
            ],
        ),
    ]
