# Generated by Django 3.1.6 on 2021-03-29 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0003_auto_20210329_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmotivator',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bookmotivator',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
