# Generated by Django 3.1.6 on 2021-04-19 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteering_module', '0002_auto_20210412_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermotivator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to=settings.AUTH_USER_MODEL),
        ),
    ]
